modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Easy-NPC/issues"

[[mods]]
modId = "easy_npc_bundle"
version = "${file.jarVersion}"
displayName = "Easy NPC: Bundle"
displayURL = "https://github.com/MarkusBordihn/BOs-Easy-NPC"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''
Bundle version of Easy NPC that automatically includes both the core mod and config UI mod using Jar-in-Jar technology.

This bundle contains:
- Easy NPC Core: Provides all NPC functionality
- Easy NPC Config UI: Provides configuration interface for NPCs

Users only need to install this single file to get both mods.
'''

[[dependencies.easy_npc_bundle]]
modId = "forge"
mandatory = true
versionRange = "[52.1.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_npc_bundle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_npc_bundle]]
modId = "easy_npc"
mandatory = true
versionRange = "[${file.jarVersion},${file.nextMajorVersion})"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_npc_bundle]]
modId = "easy_npc_config_ui"
mandatory = true
versionRange = "[${file.jarVersion},${file.nextMajorVersion})"
ordering = "NONE"
side = "BOTH"
